src/MedicalHealthAssistantWeb/Models/ErrorViewModel.cs
namespace MedicalHealthAssistantWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MedicalHealthAssistantWeb/Models/UserSigninModel.cs
namespace MedicalHealthAssistantWeb.Models;

public class UserSigninModel
{
    public string Phone { get; set;}
    public string Password {get; set;}
}

src/MedicalHealthAssistantWeb/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services;

namespace MedicalHealthAssistantWeb.Controllers;

public class DoctorController : Controller
{
    private readonly DoctorService doctorService;

    public DoctorController(DoctorService doctorService)
    {
        this.doctorService = doctorService;
    }

    public async Task<IActionResult> Index()
    {
        var result = await doctorService.GetAllDoctorsAsync();
        return View(result);
    }
    public IActionResult Create() 
    {
        return View();
    }

    public IActionResult Update()
    {
        return View();
    }

    public IActionResult Delete()
    {
        return View();
    }
}

src/MedicalHealthAssistantWeb/Controllers/HomeController.cs
using MedicalHealthAssistantWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Service.DTOs.Users;
using Service.Interfaces;
using System.Diagnostics;

namespace MedicalHealthAssistantWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IUserService userService;
    public HomeController(ILogger<HomeController> logger, IUserService userService)
    {
        _logger = logger;
        this.userService = userService;
    }

    public IActionResult Signin()
    {
        return View();
    }

    public IActionResult Signup()
    {
        return View();
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    public IActionResult AdminPage()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/MedicalHealthAssistantWeb/Controllers/HospitalController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services;

namespace MedicalHealthAssistantWeb.Controllers;

public class HospitalController : Controller
{
    public readonly HospitalService HospitalService;
    public HospitalController(HospitalService hospitalService)
    {
        HospitalService = hospitalService;
    }
    public async Task<IActionResult> Index()
    {
        var result =await  HospitalService.GetAllHospitalsAsync();
        return View(result);
    }
}

src/MedicalHealthAssistantWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Service.DTOs.Users;
using Service.Interfaces;

namespace MedicalHealthAssistantWeb.Controllers;

public class UserController : Controller
{
    private IUserService userService;
    
    public UserController(IUserService userService)
    {
        this.userService = userService;
    }

    public async Task<IActionResult> Index()
    {
        var result = await userService.GetAllUsersAsync();
        return View(result);
    }
    public IActionResult Create()
    {
        return View();
    }

    public async Task<IActionResult> Update(long id)
    {
        var result = await userService.GetAsync(id);

        return View(result);
    }
    [HttpPost]
    public async Task<IActionResult> Update(UserUpdateDto dto)
    {
        var result = await userService.UpdateAsync(dto);
        return RedirectToRoute(new { controller = "User", action = "Index"});
    }

    public async Task<IActionResult> Signin(string password,string phone)
    {
        var result = await userService.SigninAsync(phone, password);
        if(result is true)
            return RedirectToRoute(new { controller = "Home", action = "AdminPage" });
        else
            return View();
    }

    public async Task<IActionResult> Signup(UserCreationDto dto)
    {
        dto.Address = "Tashkent, Yunusobod";
        var result = await userService.CreateAsync(dto);
        return RedirectToRoute(new { controller = "Home", action = "AdminPage"});
    }

    [HttpPost]
    public async Task<IActionResult> Remove(long id)
    {
        var result = await this.userService.DeleteAsync(id);
        return RedirectToRoute(new { controller = "User", action = "Index" });
    }
}

src/MedicalHealthAssistantWeb/Views/Doctor/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Create</h3>
                        <form>
                            <div class="row">
                                <div class="col-md-6 mb-4">

                                    <div class="form-outline">
                                        <input type="text" id="firstName" class="form-control form-control-lg" />
                                        <label class="form-label" for="firstName">First Name</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4">

                                    <div class="form-outline">
                                        <input type="text" id="lastName" class="form-control form-control-lg" />
                                        <label class="form-label" for="lastName">Last Name</label>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    <div class="form-outline datepicker w-100">
                                        <input type="text" class="form-control form-control-lg" id="birthdayDate" />
                                        <label for="birthdayDate" class="form-label">Birthday</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4">

                                    <h6 class="mb-2 pb-1">Gender: </h6>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender"
                                               value="option1" checked />
                                        <label class="form-check-label" for="femaleGender">Female</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"
                                               value="option2" />
                                        <label class="form-check-label" for="maleGender">Male</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="otherGender"
                                               value="option3" />
                                        <label class="form-check-label" for="otherGender">Other</label>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        <input type="email" id="emailAddress" class="form-control form-control-lg" />
                                        <label class="form-label" for="emailAddress">Email</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        <input type="tel" id="phoneNumber" class="form-control form-control-lg" />
                                        <label class="form-label" for="phoneNumber">Phone Number</label>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">

                                    <select class="select form-control-lg">
                                        <option value="1" disabled>Choose option</option>
                                        <option value="2">Subject 1</option>
                                        <option value="3">Subject 2</option>
                                        <option value="4">Subject 3</option>
                                    </select>
                                    <label class="form-label select-label">Choose option</label>

                                </div>
                            </div>

                            <div class="mt-4 pt-2">
                                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/MedicalHealthAssistantWeb/Views/Doctor/Index.cshtml
@using Service.DTOs.Doctors;
@using Service.DTOs.Users;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<DoctorResultDto>


<div class="container overflow-hidden align-content-center">
    <div class="row gx-5 align-content-center align-items-center">
        <div class="col ">
            <h4 class="text-primary">Doctors</h4>
        </div>
        <div class="col">
            <div class="Col">
                <form asp-action="Create" asp-controller="User">
                    <button type="button" class="col btn btn-success m-3 float-end">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if(Model is not null)
        {
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <img src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                                 alt=""
                                 style="width: 45px; height: 45px"
                                 class="rounded-circle" />
                            <div class="ms-3">
                                    <p class="fw-bold mb-1">@item.FirstName @item.LastName</p>
                            </div>
                        </div>
                    </td>
                    <td>
                        <p class="fw-normal mb-1">@item.Phone</p>
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <div>
                                <form asp-action="Update" asp-controller="User" asp-route="@item.Id">
                                    <button type="submit" class="btn btn-secondary">Edit</button>
                                </form>
                            </div>
                            <div class="m-lg-3">
                                <form asp-action="remove" asp-controller="User" asp-route-id="@item.Id">
                                    <button type="submit" class="btn btn-secondary">Remove</button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

src/MedicalHealthAssistantWeb/Views/Doctor/Update.cshtml
@using Service.DTOs.Users;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model UserUpdateDto

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
                        <form>
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <input type="text" id="firstName" class="form-control form-control-lg" />
                                        <label class="form-label" for="firstName">First Name</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4">

                                    <div class="form-outline">
                                        <input type="text" id="lastName" class="form-control form-control-lg" />
                                        <label class="form-label" for="lastName">Last Name</label>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    <div class="form-outline datepicker w-100">
                                        <input type="text" class="form-control form-control-lg" id="birthdayDate" />
                                        <label for="birthdayDate" class="form-label">Birthday</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4">

                                    <h6 class="mb-2 pb-1">Gender: </h6>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender"
                                               value="option1" checked />
                                        <label class="form-check-label" for="femaleGender">Female</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"
                                               value="option2" />
                                        <label class="form-check-label" for="maleGender">Male</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="otherGender"
                                               value="option3" />
                                        <label class="form-check-label" for="otherGender">Other</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        <input type="email" id="emailAddress" class="form-control form-control-lg" />
                                        <label class="form-label" for="emailAddress">Email</label>
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        <input type="tel" id="phoneNumber" class="form-control form-control-lg" />
                                        <label class="form-label" for="phoneNumber">Phone Number</label>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">

                                    <select class="select form-control-lg">
                                        <option value="1" disabled>Choose option</option>
                                        <option value="2">Subject 1</option>
                                        <option value="3">Subject 2</option>
                                        <option value="4">Subject 3</option>
                                    </select>
                                    <label class="form-label select-label">Choose option</label>

                                </div>
                            </div>

                            <div class="mt-4 pt-2">
                                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/MedicalHealthAssistantWeb/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<body style="background-color: #B0DAFF">
    <header>
        <style>
            @@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,500;0,700;0,900;1,300&display=swap');
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color:#19A7CE; font-family: 'Roboto', sans-serif;">
            <!-- Container wrapper -->
            <div class="container-fluid w-100">
                <!-- Navbar brand -->
                <a class="navbar-brand me-0" href="https://mdbgo.com/">
                    <h3 class="text-light">HEALTH+</h3>
                </a>

                <!-- Toggle button -->
                <button class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarButtonsExample"
                        aria-controls="navbarButtonsExample"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarButtonsExample">
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-5 ">
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Doctors</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Contact</a>
                        </li>
                    </ul>

                    <!-- Left links -->

                    <div class="d-flex align-items-center">
                        <form asp-action="Signin" asp-controller="Home" method="get">
                            <button type="submit" class="btn btn-link px-3 me-2" style="color:white; text-decoration:none">
                                Sign in
                            </button>
                        </form>
                        <form asp-action="Signup" asp-controller="Home" method="get">
                            <button type="submit" class="btn btn-primary me-3" style="background-color:#146C94">
                                Sign up
                            </button>
                        </form>
                    </div>
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
    </header>

    <section style="margin:30px 10% 0 10%">
        <div class="text-center my-3">
            <h3>What is a Health Care Assistant?</h3>
        </div>
        <div class="mx-lg-5">
            <p>
                A health care assistant (HCA) is a person who provides basic nursing and personal care services to patients in hospitals, nursing homes, residential aged care facilities, community health centers, and clients’ homes.
                <br />
                Healthcare assistants work under the supervision of registered nurses and other health professionals. They play an important role in providing quality care and support to patients and clients.
            </p>
            <img src="https://cdn-hibhh.nitrocdn.com/cSmWTHYMVIExXzmhiWSuqcypazGVPyGD/assets/images/optimized/rev-e51b0f8/wcc.ca/wp-content/uploads/2023/02/What-is-a-Health-Care-Assistant.jpg" class="img-fluid" alt="img">

            <div class="text-center my-3">
                <h3>What is a Health Care Assistant?</h3>
            </div>

            <p>
                As a Health Care Assistant, your primary responsibilities will include providing personal care to patients, such as bathing, dressing, and feeding, as well as helping with activities of daily living. You will also assist with mobility and transfers, take vital signs, and perform basic health observations.
                <br />
                In addition to hands-on care, you will also be responsible for maintaining a clean and safe environment for patients and ensuring their comfort and well-being. This may include making beds, doing laundry, and tidying the patient’s room.
            </p>

            <div class="text-center my-3">
                <h3>Is a Health Care Assistant a Nurse?</h3>
            </div>
            
            <p>
                No, a Health Care Assistant is not a nurse. While HCAs and nurses work in the healthcare industry and provide care to patients, their roles and responsibilities differ.
                <br />
                Nurses are licensed healthcare professionals who have completed extensive training and education and are responsible for administering medications, creating and implementing care plans, and supervising HCAs and other healthcare staff.
            </p>

        </div>
    </section>
</body>

<style>
    p{
        font-size:20px;
    }
</style>

src/MedicalHealthAssistantWeb/Views/Home/AdminPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <img src="https://i.mycdn.me/i?r=AzHURLEKCKeOPiAJVsvbTSR6ztdMze4lCrxBD3_gzwXKLzIQNnYRNKxMEpZsQwM7G9U"
             alt="Logo"
             style="width: 100px; height: 80px"
             class="rounded-circle"/>

        <button class="navbar-toggler"
                type="button"
                data-mdb-toggle="collapse"
                data-mdb-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","User")">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Doctor")">Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Hospital")">Hospital</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Doctor")">Doctor</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/MedicalHealthAssistantWeb/Views/Home/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<body style="background-color: #B0DAFF">
    <header>
        <style>
            @@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,500;0,700;0,900;1,300&display=swap');
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color:#19A7CE; font-family: 'Roboto', sans-serif;">
            <!-- Container wrapper -->
            <div class="container-fluid w-100">
                <!-- Navbar brand -->
                <a class="navbar-brand me-0" href="https://mdbgo.com/">
                    <h3 class="text-light">HEALTH+</h3>
                </a>

                <!-- Toggle button -->
                <button class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarButtonsExample"
                        aria-controls="navbarButtonsExample"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarButtonsExample">
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-5 ">
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Doctors</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Contact</a>
                        </li>
                    </ul>

                    <!-- Left links -->

                    <div class="d-flex align-items-center">
                        <form asp-action="Signin" asp-controller="Home" method="get">
                            <button type="submit" class="btn btn-link px-3 me-2" style="color:white; text-decoration:none">
                                Sign in
                            </button>
                        </form>
                        <form asp-action="Signup" asp-controller="Home" method="get">
                            <button type="submit" class="btn btn-primary me-3" style="background-color:#146C94">
                                Sign up
                            </button>
                        </form>
                    </div>
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
    </header>
    <div class="container mt-3">
       <div class="row">
            <div class="col-sm">
                <div class="d-flex align-items-center">
                    <img src="https://samoapools.com/contents/images/Customer-service-woman-on-headset-gives-OK-1024x770.jpg"
                         alt="Logo"
                         style="width: 100px; height: 80px"
                         class="rounded-circle" />
                    <div class="ms-3">
                        <p class="fw-bold mb-1">Operator Alisa</p>
                        <p class="text-muted mb-0">Phone: +9988776655</p>
                    </div>
                </div>
                <div style="margin-top:30px;">
                    
                    <img src="~/Icons/tm.png"
                         alt=""
                         style="width: 45px; height: 45px"
                         class="rounded-circle" />
                    <img src="~/Icons/instagram.png"
                         alt=""
                         style="width: 45px; height: 45px"
                         class="rounded-circle" />
                    <img src="~/Icons/facebook.png"
                         alt=""
                         style="width: 45px; height: 45px"
                         class="rounded-circle" />
                </div>

            </div>
            <div class="col-sm h-50 mt-3" style="width:40%;background-color:#19A7CE; border-radius:4px;">

                <!-- Default form contact -->
                <form class="text-center border border-light p-5" action="#!">

                    <p class="h4 mb-4">Contact us</p>

                    <!-- Name -->
                    <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name">

                    <!-- Email -->
                    <input type="tel" id="defaultContactFormEmail" class="form-control mb-4" placeholder="phone">



                    <!-- Message -->
                    <div class="form-group">
                        <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="3" placeholder="Message"></textarea>
                    </div>

                    <!-- Copy -->
                    <div class="custom-control custom-checkbox mb-4">
                        <input type="checkbox" class="custom-control-input" id="defaultContactFormCopy">
                        <label class="custom-control-label" for="defaultContactFormCopy">Send me a copy of this message</label>
                    </div>

                    <!-- Send button -->
                    <button class="btn btn-info btn-block" type="submit">Send</button>

                </form>
            </div>
       </div> 
    </div>
    <!-- Default form contact -->


</body>